import React, { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { supabase, isSupabaseConfigured } from '../lib/supabase'

export function Login() {
  const navigate = useNavigate(); const location = useLocation()
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(e){ e.preventDefault(); setError(''); if(!supabase){setError('Connect Supabase first. See .env.example.');return} setBusy(true); const {error}=await supabase.auth.signInWithPassword({email,password}); setBusy(false); if(error){setError(error.message);return} navigate(location.state?.from || '/dashboard') }
  return <AuthLayout title="Welcome back" subtitle="Sign in to manage your Reway marketplace activity."><form className="auth-form" onSubmit={submit}><label>Work email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@company.com"/></label><label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required placeholder="••••••••"/></label>{error&&<div className="error-box">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><p className="auth-switch">Don't have an account? <Link to="/signup">Create one</Link></p></AuthLayout>
}

export function Signup() {
  const navigate=useNavigate(); const [form,setForm]=useState({name:'',company:'',email:'',password:'',role:'seller'}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const update=(k,v)=>setForm({...form,[k]:v})
  async function submit(e){ e.preventDefault(); setError(''); if(!supabase){setError('Connect Supabase first. See .env.example.');return} setBusy(true); const {data,error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.name,company_name:form.company,role:form.role}}}); if(error){setBusy(false);setError(error.message);return} if(data.user){await supabase.from('profiles').upsert({id:data.user.id,full_name:form.name,company_name:form.company,role:form.role});} setBusy(false); navigate('/dashboard') }
  return <AuthLayout title="Create your Reway account" subtitle="Join the digital marketplace for e-waste transactions."><form className="auth-form" onSubmit={submit}><label>Account type<div className="role-picker"><button type="button" className={form.role==='seller'?'selected':''} onClick={()=>update('role','seller')}><b>Sell e-waste</b><span>List material and receive quotes.</span></button><button type="button" className={form.role==='recycler'?'selected':''} onClick={()=>update('role','recycler')}><b>Buy e-waste</b><span>Discover listings and submit quotes.</span></button></div></label><label>Full name<input value={form.name} onChange={e=>update('name',e.target.value)} required/></label><label>Company name<input value={form.company} onChange={e=>update('company',e.target.value)} required/></label><label>Work email<input value={form.email} onChange={e=>update('email',e.target.value)} type="email" required/></label><label>Password<input value={form.password} onChange={e=>update('password',e.target.value)} type="password" minLength="8" required/></label>{error&&<div className="error-box">{error}</div>}<button className="primary-btn" disabled={busy}>{busy?'Creating…':'Create account'}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthLayout>
}

function AuthLayout({title,subtitle,children}){ return <div className="auth-page"><div className="auth-card"><Link to="/" className="auth-logo"><span className="brand-dot">R</span> REWAY</Link><div className="auth-heading"><span className="eyebrow">MARKETPLACE ACCESS</span><h1>{title}</h1><p>{subtitle}</p></div>{!isSupabaseConfigured&&<div className="warning-box">Supabase is not configured yet. Add your VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to <code>.env.local</code>.</div>}{children}</div></div> }
