import React, {useEffect, useState} from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../lib/auth';
import "../landing.css";

const Arrow = ({small=false}) => <span className={small?'arrow small':'arrow'}>↗</span>;
const Logo = () => <Link className="brand" to="/" aria-label="Reway home"><span className="brand-mark"><i></i><b></b></span><span>REWAY</span></Link>;

const nav = [['Home','/'],['Our Services','/services'],['Marketplace','/marketplace']];
const listings = [
 {type:'IT Equipment', qty:'1,240 kg', loc:'Delhi NCR', condition:'Mixed / working', tag:'Corporate lot'},
 {type:'Printed Circuit Boards', qty:'480 kg', loc:'Gurugram', condition:'Sorted', tag:'High-value stream'},
 {type:'Lithium-ion Batteries', qty:'760 kg', loc:'Noida', condition:'End-of-life', tag:'Battery waste'},
 {type:'Mixed Electronics', qty:'2.1 t', loc:'Bengaluru', condition:'Assorted', tag:'Demo listing'},
];
const stakeholders = ['Businesses','Recyclers','Refurbishers','Logistics','Material Buyers','Collection Partners'];
const steps = [
 ['01','LIST','Upload your e-waste or battery-waste details.'],
 ['02','DISCOVER','Relevant recyclers discover available material.'],
 ['03','MATCH','Connect with suitable ecosystem participants.'],
 ['04','MOVE','Logistics partners facilitate transportation.'],
 ['05','RECYCLE','Material is processed and valuable resources recovered.'],
 ['06','RECIRCULATE','Recovered materials can be listed again.'],
];

export default function LandingPage(){
 const { user, profile, signOut } = useAuth();
 const [menu,setMenu]=useState(false); const [scrolled,setScrolled]=useState(false);
 const role = profile?.role || user?.user_metadata?.role;
 const accountPath = role === 'recycler' ? '/marketplace' : '/dashboard';
 useEffect(()=>{const f=()=>setScrolled(scrollY>20);addEventListener('scroll',f);return()=>removeEventListener('scroll',f)},[]);
 return <div id="top" className="site">
  <header className={scrolled?'nav scrolled':'nav'}><div className="nav-inner"><Logo/><nav className={menu?'open':''}>{nav.map(([n,h])=><Link key={n} to={h} onClick={()=>setMenu(false)}>{n}</Link>)}<a href="#about" onClick={()=>setMenu(false)}>About</a><a href="#contact" onClick={()=>setMenu(false)}>Contact</a>{user ? <><Link to={accountPath} onClick={()=>setMenu(false)}>My Account</Link><button className="nav-cta" type="button" onClick={async()=>{await signOut();setMenu(false)}}>Sign Out <Arrow small/></button></> : <><Link to="/login" onClick={()=>setMenu(false)}>Login</Link><Link className="nav-cta" to="/signup?role=seller" onClick={()=>setMenu(false)}>Sell Waste <Arrow small/></Link></>}</nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?'×':'☰'}</button></div></header>
  <main>
   <section className="hero"><div className="hero-grid"></div><div className="container hero-wrap">
    <div className="eyebrow"><span className="pulse"></span> DIGITAL INFRASTRUCTURE FOR CIRCULARITY</div>
    <h1>The digital infrastructure<br/>for a <em>circular economy.</em></h1>
    <p className="hero-copy">Reway connects e-waste and battery-waste stakeholders through one technology ecosystem — enabling marketplaces, traceability and intelligence from generation to recovery.</p>
    <div className="actions"><Link className="btn primary" to="/signup?role=seller">Sell Waste <Arrow/></Link><Link className="btn ghost" to="/marketplace">Explore Marketplace <Arrow small/></Link></div>
    <div className="hero-trust"><span>Built for</span><b>Businesses</b><i>·</i><b>Recyclers</b><i>·</i><b>Logistics</b><i>·</i><b>Material buyers</b></div>
   </div>
   <div className="hero-visual" aria-label="Illustration of Reway's connected circular economy network">
    <div className="orbit o1"></div><div className="orbit o2"></div><div className="orbit o3"></div><div className="core"><div className="core-logo">R</div><span>REWAY<br/><small>NETWORK</small></span></div>
    {['SELLER','RECYCLER','LOGISTICS','MATERIALS','AI INTELLIGENCE','TRACEABILITY'].map((x,i)=><div key={x} className={'node n'+i}><span></span><b>{x}</b></div>)}
    <svg className="hero-lines" viewBox="0 0 900 650" preserveAspectRatio="none"><path d="M150 120 C320 90 350 270 450 325 S620 560 770 520"/><path d="M130 420 C290 510 320 350 450 325 S650 100 800 170"/><path d="M450 325 C500 250 560 170 690 120"/></svg>
   </div></section>

   <section className="signal"><div className="container signal-row"><div><span className="kicker">THE GAP</span><h2>A fragmented system<br/><strong>needs a connected layer.</strong></h2></div><div className="signal-copy">E-waste moves through sellers, collectors, logistics providers and recyclers — often with limited discovery and visibility. Reway brings the network onto one digital layer.</div><div className="signal-metrics"><div><b>01</b><span>Fragmented<br/>stakeholders</span></div><div><b>02</b><span>Limited<br/>visibility</span></div><div><b>03</b><span>Lost material<br/>value</span></div></div></div></section>

   <section id="platform" className="section platform"><div className="container"><div className="section-head"><div><span className="kicker">THE PLATFORM</span><h2>One network.<br/><em>Multiple material flows.</em></h2></div><p>Reway is not another collection service. It is the technology layer connecting the circular economy — from listings and matching to movement, recovery and resale.</p></div>
    <div className="network-card"><div className="network-center"><div className="mini-orbit"></div><strong>REWAY</strong><span>digital ecosystem</span></div>{[['SELLERS',12,19],['RECYCLERS',73,18],['LOGISTICS',8,72],['REFURBISHERS',76,73],['MATERIAL BUYERS',44,7],['COLLECTION',45,89]].map(([x,l,t])=><div className="network-node" style={{left:l+'%',top:t+'%'}} key={x}><span></span>{x}</div>)}<svg viewBox="0 0 1000 500" preserveAspectRatio="none"><path d="M150 95 Q500 250 750 90"/><path d="M100 360 Q500 250 790 360"/><path d="M450 35 Q500 250 500 450"/><path d="M150 95 Q260 250 100 360"/><path d="M750 90 Q640 250 790 360"/></svg></div>
   </div></section>

   <section id="how" className="section how"><div className="container"><div className="section-head centered"><div><span className="kicker">HOW IT WORKS</span><h2>From waste stream<br/><em>to material stream.</em></h2></div></div><div className="steps">{steps.map(([num,title,desc],i)=><div className="step" key={num}><div className="step-top"><span>{num}</span><span className="step-dot"></span></div><h3>{title}</h3><p>{desc}</p>{i<5&&<div className="step-line"></div>}</div>)}</div><div className="manifest"><span>Reway circular manifest</span><b>Waste generated</b><i>→</i><b>Listed</b><i>→</i><b>Matched</b><i>→</i><b>Transported</b><i>→</i><b>Recycled</b><i>→</i><b>Recovered</b><i>→</i><b>Resold</b></div></div></section>

   <section className="section marketplace"><div className="container"><div className="section-head"><div><span className="kicker">DIGITAL MARKETPLACE</span><h2>Discover material.<br/><em>Find the next match.</em></h2></div><p>Example interface data shown for demonstration. In production, marketplace inventory can connect to Reway's backend and participant workflows.</p></div><div className="market-layout"><div className="listing-panel"><div className="panel-top"><b>Available material</b><span>DEMO DATA · 04 LISTINGS</span></div>{listings.map((x,i)=><div className="listing" key={x.type}><div className="material-icon">{['⌘','▦','◈','◌'][i]}</div><div className="listing-main"><b>{x.type}</b><span>{x.qty} · {x.loc}</span></div><span className="condition">{x.condition}</span><Link to="/marketplace" className="listing-link">View marketplace <Arrow small/></Link></div>)}</div><div className="market-side"><div className="quote-card"><span className="card-label">RECOVERED MATERIALS</span><h3>Put recovered value<br/>back in motion.</h3><p>Recyclers can list recovered metals and materials for buyers — extending the marketplace beyond waste.</p><div className="metal"><span>Cu</span><b>Copper</b><small>Recovered material</small><i>→</i></div><div className="metal"><span>Al</span><b>Aluminium</b><small>Recovered material</small><i>→</i></div></div></div></div></div></section>

   <section className="section trace"><div className="container"><div className="trace-layout"><div><span className="kicker">TRACEABILITY</span><h2>See where the<br/><em>material is moving.</em></h2><p>Supply-chain visibility across movement, handoffs and processing — giving ecosystem participants a clearer digital journey.</p><a href="#contact" className="text-link">Talk to us about traceability <Arrow small/></a></div><div className="trace-card"><div className="trace-header"><span>LIVE MATERIAL JOURNEY</span><b>Illustrative</b></div><div className="timeline">{[['GENERATOR','Material listed','09:14 · Delhi NCR'],['COLLECTION','Pickup scheduled','11:32 · Gurugram'],['LOGISTICS','In transit','14:08 · NCR'],['RECYCLER','Received & processing','16:41 · Faridabad'],['RECOVERY','Materials recovered','— · Processing']].map((x,i)=><div className="event" key={x[0]}><div className="event-dot"><span></span></div><div><b>{x[0]}</b><strong>{x[1]}</strong><small>{x[2]}</small></div>{i<4&&<div className="event-connector"/>}</div>)}</div></div></div></div></section>

   <section id="technology" className="section tech"><div className="container"><div className="section-head"><div><span className="kicker">TECHNOLOGY LAYER</span><h2>Infrastructure for<br/><em>better decisions.</em></h2></div><p>Reway combines marketplace infrastructure, traceability and data intelligence into a single ecosystem layer.</p></div><div className="tech-grid"><div className="tech-card price"><div className="card-top"><span>AI PRICE INTELLIGENCE</span><span className="live">● ILLUSTRATIVE</span></div><h3>Know the value<br/>before you move it.</h3><p>AI-based e-waste price prediction can help participants understand expected market pricing and make better decisions.</p><div className="chart"><div className="chart-meta"><span>Illustrative price trend</span><b>₹ / kg</b></div><svg viewBox="0 0 620 180" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#78f58b" stopOpacity=".25"/><stop offset="1" stopColor="#78f58b" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 140 C70 128 85 98 150 116 S220 72 275 95 S345 40 410 72 S480 30 540 58 S590 18 620 24 V180 H0Z"/><path className="line" d="M0 140 C70 128 85 98 150 116 S220 72 275 95 S345 40 410 72 S480 30 540 58 S590 18 620 24"/></svg><div className="chart-values"><span>Historical</span><b>Predicted range</b><span>Market movement</span></div></div></div><div className="tech-stack"><div className="stack-title">REWAY / CORE LAYER</div>{[['01','Marketplace infrastructure'],['02','Supply-chain traceability'],['03','AI price intelligence'],['04','Data & analytics'],['05','Digital ecosystem'],['06','Future-ready integrations']].map(x=><div className="stack-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><Arrow small/></div>)}</div></div></div></section>

   <section className="section stakeholders"><div className="container"><div className="section-head centered"><div><span className="kicker">ONE ECOSYSTEM</span><h2>Every participant.<br/><em>One connected layer.</em></h2></div></div><div className="stake-grid">{stakeholders.map((s,i)=><div className="stake" key={s}><span>0{i+1}</span><div className="stake-icon">{['◫','♻','◇','↗','◉','⌁'][i]}</div><h3>{s}</h3><p>Connect, discover and move material through a shared digital ecosystem.</p></div>)}</div></div></section>

   <section id="businesses" className="section persona"><div className="container persona-grid"><div className="persona-copy"><span className="kicker">FOR BUSINESSES</span><h2>Turn disposal<br/>into a <em>digital workflow.</em></h2><p>Give bulk generators a clearer way to list e-waste, discover relevant recyclers and track material movement through its next destination.</p><ul>{['Digitally list e-waste','Discover relevant recyclers','Compare marketplace opportunities','Track material movement','Improve visibility across disposal'].map(x=><li key={x}><span>✓</span>{x}</li>)}</ul><Link className="btn primary" to="/signup?role=seller">List Your Waste <Arrow/></Link></div><div className="persona-ui"><div className="window"><div className="window-bar"><span></span><span></span><span></span><b>reway / seller workspace</b></div><div className="workspace"><aside><div className="side-logo">R</div><span className="active">Listings</span><span>Pickups</span><span>Quotes</span><span>Tracking</span></aside><div className="dash"><div className="dash-title"><b>Material overview</b><span>+ New listing</span></div><div className="dash-cards"><div><small>ACTIVE LISTINGS</small><b>08</b></div><div><small>QUOTES RECEIVED</small><b>23</b></div><div><small>IN TRANSIT</small><b>03</b></div></div><div className="dash-table"><div><b>Material</b><b>Quantity</b><b>Status</b></div>{['IT equipment','PCBs','Lithium batteries'].map((x,i)=><div key={x}><span>{x}</span><span>{['1.2 t','480 kg','760 kg'][i]}</span><em>{['Matched','Listed','In transit'][i]}</em></div>)}</div></div></div></div></div></div></section>

   <section id="recyclers" className="section recycler"><div className="container persona-grid reverse"><div className="recycler-visual"><div className="radar"><span className="radar-ring r1"></span><span className="radar-ring r2"></span><span className="radar-ring r3"></span><span className="radar-core">R</span>{['IT','PCB','BAT','Cu','Al'].map((x,i)=><b key={x} style={{'--i':i}}>{x}</b>)}</div><div className="radar-caption"><span>RECYCLER NETWORK</span><b>Discover supply<br/>across categories</b></div></div><div className="persona-copy"><span className="kicker">FOR RECYCLERS</span><h2>Grow your supply<br/><em>network digitally.</em></h2><p>Discover available e-waste, connect with sellers, coordinate movement and list recovered materials for the next buyer.</p><ul>{['Discover available e-waste','Access a larger supply network','Acquire material through the marketplace','Connect movement through logistics','List recovered metals/materials'].map(x=><li key={x}><span>✓</span>{x}</li>)}</ul><Link className="btn secondary" to="/signup?role=recycler">Join as a Recycler <Arrow/></Link></div></div></section>

   <section className="loop"><div className="container loop-inner"><div><span className="kicker">CLOSE THE LOOP</span><h2>Waste doesn't have<br/>to be the <em>end.</em></h2><p>Build a system where material keeps moving — through marketplaces, logistics, recovery and back into productive use.</p></div><div className="loop-wheel"><div className="wheel-ring"></div>{['GENERATE','LIST','MATCH','MOVE','RECYCLE','RECOVER','RESELL'].map((x,i)=><b key={x} style={{'--i':i}}>{x}</b>)}<div className="wheel-center">MATERIAL<br/><strong>FLOW</strong></div></div></div></section>

   <section id="about" className="section about"><div className="container about-grid"><div><span className="kicker">ABOUT REWAY</span><h2>Building the<br/><em>next layer of circularity.</em></h2></div><div><p className="lead">Reway started with a simple observation: e-waste is valuable, but the system around it is fragmented.</p><p>We are building technology infrastructure that connects sellers, recyclers, logistics providers and material buyers — making the movement and exchange of material more visible, discoverable and data-driven.</p><p>Our existing journey is rooted in digitising the gap between e-waste sellers and authorised recyclers; the next chapter is a broader circular marketplace and ecosystem.</p></div></div></section>

   <section id="contact" className="cta"><div className="container cta-inner"><div><span className="kicker">START WITH REWAY</span><h2>Build the circular<br/><em>economy with us.</em></h2><p>Tell us what you want to move, recover or connect.</p></div><form onSubmit={e=>e.preventDefault()}><div className="form-row"><input placeholder="Your name"/><input type="email" placeholder="Work email"/></div><select defaultValue=""><option value="" disabled>I am interested in…</option><option>Listing e-waste</option><option>Joining as a recycler</option><option>Logistics / collection</option><option>Material buying</option><option>Partnership</option></select><textarea rows="3" placeholder="Tell us a little about your requirement"></textarea><button className="btn primary" type="submit">Send enquiry <Arrow/></button></form></div></section>
  </main>
  <footer><div className="container footer-grid"><div><Logo/><p>Digital infrastructure for a circular economy.</p><a href="mailto:reway.ewm@gmail.com">reway.ewm@gmail.com</a><br/><a href="tel:+919315836383">+91 93158 36383</a></div><div><b>Platform</b><a href="#platform">Marketplace</a><a href="#how">How it works</a><a href="#technology">Technology</a></div><div><b>For participants</b><a href="#businesses">Businesses</a><a href="#recyclers">Recyclers</a><a href="#contact">Logistics & buyers</a></div><div><b>Company</b><a href="#about">About Reway</a><a href="#contact">Contact</a><a href="https://www.reway.co.in/" target="_blank" rel="noreferrer">Current website ↗</a></div></div><div className="container footer-bottom"><span>© 2026 Reway Technologies. All rights reserved.</span><span>Marketplace · Traceability · Intelligence · Circularity</span></div></footer>
 </div>
}
