import React, { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { Empty } from './Dashboard'

export function MyListings(){
 const {profile}=useAuth(); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true)
 async function load(){ if(!supabase||!profile)return; setLoading(true); const {data}=await supabase.from('listings').select('*').eq('seller_id',profile.id).order('created_at',{ascending:false}); setRows(data||[]); setLoading(false)}
 useEffect(()=>{load()},[profile])
 return <section className="panel"><div className="panel-head"><div><span className="eyebrow">SELLER</span><h3>My listings</h3></div><Link to="/listings/new" className="primary-btn small-btn">+ List e-waste</Link></div>{loading?<div className="loading-box">Loading…</div>:rows.length===0?<Empty text="No listings yet."/>:<div className="listing-grid">{rows.map(x=><ListingCard key={x.id} item={x}/>)}</div>}</section>
}

export function Marketplace(){
 const {profile}=useAuth(); const [rows,setRows]=useState([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true)
 useEffect(()=>{async function load(){if(!supabase){setLoading(false);return} const {data}=await supabase.from('listings').select('*,seller:profiles(full_name,company_name)').eq('status','PUBLISHED').order('created_at',{ascending:false}); setRows(data||[]);setLoading(false)} load()},[])
 const filtered=rows.filter(x=>`${x.title} ${x.material_type} ${x.location}`.toLowerCase().includes(search.toLowerCase()))
 return <><div className="welcome-row"><div><span className="eyebrow">MARKETPLACE</span><h2>Available e-waste</h2><p>Discover published material listings and submit a quotation.</p></div></div><div className="search-bar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search material, category or location…"/></div>{loading?<div className="loading-box">Loading marketplace…</div>:filtered.length===0?<div className="panel"><Empty text="No published listings match your search."/></div>:<div className="listing-grid">{filtered.map(x=><ListingCard key={x.id} item={x} recycler={profile?.role==='recycler'}/>)}</div>}</>
}

function ListingCard({item,recycler}){return <article className="listing-card"><div className="listing-top"><span className="category-tag">{item.category||'E-waste'}</span><span className="status-pill">{item.status}</span></div><h3>{item.title}</h3><div className="listing-meta"><div><span>Quantity</span><b>{item.quantity} {item.unit}</b></div><div><span>Location</span><b>{item.location}</b></div><div><span>Condition</span><b>{item.condition||'—'}</b></div></div>{item.description&&<p>{item.description.slice(0,120)}{item.description.length>120?'…':''}</p>}<Link to={`/listings/${item.id}`} className="card-link">View listing ↗</Link></article>}

export function NewListing(){
 const {profile}=useAuth(); const navigate=useNavigate(); const [form,setForm]=useState({title:'',category:'IT Equipment',material_type:'',quantity:'',unit:'kg',condition:'End-of-life',location:'',pickup_date:'',pickup_time:'',description:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 const set=(k,v)=>setForm({...form,[k]:v})
 async function submit(e){e.preventDefault();setError('');if(!supabase){setError('Configure Supabase first.');return}setBusy(true);const payload={...form,seller_id:profile.id,quantity:Number(form.quantity),status:'PUBLISHED'};const {data,error}=await supabase.from('listings').insert(payload).select().single();if(error){setError(error.message);setBusy(false);return}await supabase.from('status_events').insert({listing_id:data.id,status:'PUBLISHED',note:'Listing published by seller'});setBusy(false);navigate(`/listings/${data.id}`)}
 return <section className="panel form-panel"><div className="panel-head"><div><span className="eyebrow">SELLER</span><h3>List e-waste</h3><p>Create a marketplace listing for recyclers to discover and quote on.</p></div></div><form className="data-form" onSubmit={submit}><div className="form-grid"><Field label="Listing title"><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="e.g. Corporate laptop lot" required/></Field><Field label="Category"><select value={form.category} onChange={e=>set('category',e.target.value)}><option>IT Equipment</option><option>Printed Circuit Boards</option><option>Lithium-ion Batteries</option><option>Mixed Electronics</option><option>Other E-waste</option></select></Field><Field label="Material type"><input value={form.material_type} onChange={e=>set('material_type',e.target.value)} placeholder="e.g. End-of-life laptops" required/></Field><Field label="Quantity"><div className="input-pair"><input type="number" min="0.01" step="0.01" value={form.quantity} onChange={e=>set('quantity',e.target.value)} required/><select value={form.unit} onChange={e=>set('unit',e.target.value)}><option>kg</option><option>tonnes</option><option>units</option></select></div></Field><Field label="Condition"><select value={form.condition} onChange={e=>set('condition',e.target.value)}><option>End-of-life</option><option>Mixed</option><option>Working</option><option>Non-working</option><option>Sorted</option></select></Field><Field label="Pickup location"><input value={form.location} onChange={e=>set('location',e.target.value)} placeholder="Noida, Uttar Pradesh" required/></Field><Field label="Preferred pickup date"><input type="date" value={form.pickup_date} onChange={e=>set('pickup_date',e.target.value)}/></Field><Field label="Preferred pickup time"><input type="time" value={form.pickup_time} onChange={e=>set('pickup_time',e.target.value)}/></Field></div><Field label="Description"><textarea rows="5" value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Describe the material, approximate composition, packaging, pickup context, etc."/></Field>{error&&<div className="error-box">{error}</div>}<div className="form-actions"><button type="button" className="secondary-btn" onClick={()=>navigate('/my-listings')}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Publishing…':'Publish listing'}</button></div></form></section>
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
