import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'

const statuses=['ORDER_CONFIRMED','PICKUP_SCHEDULED','PICKED_UP','IN_TRANSIT','RECEIVED','COMPLETED']
export function Orders(){const {profile}=useAuth();const [rows,setRows]=useState([]);useEffect(()=>{if(!supabase||!profile)return;const key=profile.role==='seller'?'seller_id':'recycler_id';supabase.from('orders').select('*,listing:listings(title,quantity,unit,location)').eq(key,profile.id).order('created_at',{ascending:false}).then(({data})=>setRows(data||[]))},[profile]);return <section className="panel"><div className="panel-head"><div><span className="eyebrow">TRANSACTIONS</span><h3>Orders</h3></div></div>{rows.length===0?<div className="empty"><div>□</div><p>No orders yet.</p></div>:<div className="order-list">{rows.map(o=><Link to={`/orders/${o.id}`} className="order-row" key={o.id}><div><b>{o.listing?.title||'E-waste order'}</b><span>#{o.id.slice(0,8)} · {o.listing?.location}</span></div><span className="status-pill">{o.status}</span><strong>View ↗</strong></Link>)}</div>}</section>}

export function OrderDetail(){const {id}=useParams();const {profile}=useAuth();const [order,setOrder]=useState(null);const [events,setEvents]=useState([]);const [busy,setBusy]=useState(false);const allowed=profile?.role==='recycler';
 async function load(){if(!supabase)return;const {data}=await supabase.from('orders').select('*,listing:listings(*),seller:profiles!orders_seller_id_fkey(full_name,company_name),recycler:profiles!orders_recycler_id_fkey(full_name,company_name)').eq('id',id).single();setOrder(data);const {data:e}=await supabase.from('status_events').select('*').eq('order_id',id).order('created_at',{ascending:true});setEvents(e||[])}
 useEffect(()=>{load()},[id])
 async function advance(){if(!order)return;const i=statuses.indexOf(order.status);if(i<0||i>=statuses.length-1)return;setBusy(true);const next=statuses[i+1];const {error}=await supabase.from('orders').update({status:next}).eq('id',id);if(!error)await supabase.from('status_events').insert({order_id:id,status:next,note:`Status updated to ${next}`});setBusy(false);load()}
 if(!order)return <div className="loading-box">Loading order…</div>; const i=statuses.indexOf(order.status)
 return <div className="detail-grid"><section className="panel detail-main"><div className="listing-top"><span className="category-tag">ORDER</span><span className="status-pill">{order.status}</span></div><h2>Order #{order.id.slice(0,8)}</h2><div className="detail-facts"><Fact label="Material" value={order.listing?.title}/><Fact label="Quantity" value={`${order.listing?.quantity||''} ${order.listing?.unit||''}`}/><Fact label="Location" value={order.listing?.location}/><Fact label="Seller" value={order.seller?.company_name||'—'}/><Fact label="Recycler" value={order.recycler?.company_name||'—'}/></div><div className="order-timeline">{statuses.map((s,n)=><div className={n<=i?'order-step active':''} key={s}><span>{n<=i?'✓':n+1}</span><div><b>{s.replaceAll('_',' ')}</b><small>{events.find(e=>e.status===s)?.created_at?new Date(events.find(e=>e.status===s).created_at).toLocaleString():'Pending'}</small></div></div>)}</div></section><section className="panel"><span className="eyebrow">OPERATIONS</span><h3>Update status</h3><p className="muted">For the MVP, the recycler advances operational milestones. Admins can intervene when needed.</p>{allowed&&i<statuses.length-1?<button className="primary-btn" disabled={busy} onClick={advance}>{busy?'Updating…':`Mark ${statuses[i+1].replaceAll('_',' ')}`}</button>:<div className="success-box">{order.status==='COMPLETED'?'Transaction completed.':'Waiting for the next operational milestone.'}</div>}</section></div>}
function Fact({label,value}){return <div><span>{label}</span><b>{value||'—'}</b></div>}
